# Generated by Django 3.2.7 on 2021-09-21 09:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WatsonPerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('add_Users', 'Can add the Users'), ('change_Users', 'Can change the Users'), ('delete_Users', 'Can delete the Users'), ('add_Intents', 'Can add the intents'), ('change_Intents', 'Can change the intents'), ('delete_Intents', 'Can delete the intents'), ('add_Entities', 'Can add the Entities'), ('change_Entities', 'Can change the Entities'), ('delete_Entities', 'Can delete the Entities'), ('add_Dialog', 'Can add the Dialog'), ('change_Dialog', 'Can change the Dialog'), ('delete_Dialog', 'Can delete the Dialog'), ('add_Organizations', 'Can add the Organizations'), ('change_Organizations', 'Can change the Organizations'), ('delete_Organizations', 'Can delete the Organizations'), ('add_Roles', 'Can add the Roles'), ('change_Roles', 'Can change the Roles'), ('delete_Roles', 'Can delete the Roles'), ('add_Emails', 'Can add the Emails'), ('change_Emails', 'Can change the Emails'), ('delete_Emails', 'Can delete the Emails')],
            },
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
